venue_usage_profile:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres
      user: db_user
      password: db_password
      port: 5432
      dbname: dbt_db
      schema: privilee
      threads: 4